name: Create Azure DevOps repositories
on: 
 workflow_dispatch:
jobs:
  create-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
