name: Create Azure DevOps repositories
on: 
 workflow_dispatch:
jobs:
  create-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run repo creation script
        run: python scripts/create_repos.py --org 'https://dev.azure.com/jvilasbo/' --project_name 'novobanco-test' --project_id '44dd166b-18b4-48f8-98ba-fac7205e1e72' --pat '7x2F1G5wq7ilPCh130ijU10RWlRYXFEjyhF1RmE0sUkbA92x45Z1JQQJ99BEACAAAAAH2IElAAASAZDOYWQt' --input data/repos.json

        
